# Generated by Django 4.1.3 on 2023-01-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_denoising',
        ),
    ]
