# Generated by Django 4.1.5 on 2023-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_denoising',
            name='denoised_image',
            field=models.BinaryField(),
        ),
    ]
