# Generated by Django 4.1.5 on 2023-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_denoising',
            name='denoised_image',
            field=models.CharField(max_length=500),
        ),
    ]
